### ISSUE TITLE
Completion sometimes cuts following line / word

### ISSUE THREAD

**Issue by ghost** [AlonTzarafi/battle-haxe#3]
- Emacs 26.3
- Linux (Pop!_OS 19.10 a.k.a Ubuntu 19.10)
- Spacemacs User? Yes

Sometimes when selecting a completion (company) the following line is deleted. (It does not happen for other completion modes).  

The misbehavior happens only occasionally and, it seems to me, unpredictably.  I wish I could provide more information.  Any thoughts? 

(edit: I should say that it isn't too big of a deal, I just undo whenever it happens. Repeating the completion usually then works after an undo.)

**Comment by AlonTzarafi** [comment]
It happened to me before and did seem unpredictable, but now I was looking for it I managed to narrow it down.
I've pushed a fix: https://github.com/AlonTzarafi/battle-haxe/commit/64d20c9ea3fd503fdefafda122e7095c192e72a3

**Comment by ghost** [comment]
Seems to be working for me!

**Comment by AlonTzarafi** [comment]
great!
